import "./styles.css";
import { Button, Dropdown } from "semantic-ui-react";
//import { getDataTable } from "./api.js";

export default function App() {
  //let dataTable = getDataTable();
  let optionsDrop = [
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.ADMIN.SK",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.ADMIN.SK",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.ADMIN.SK"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.HE.SK",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.HE.SK",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.HE.SK"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.NEMAK",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.NEMAK",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.NEMAK"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.PRINT.SK",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.PRINT.SK",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.PRINT.SK"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.SK",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.SK",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.SK"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.SW.SK",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.SW.SK",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.SW.SK"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX.IMAC",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX.IMAC",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX.IMAC"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX.POLANCO",
      value: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX.POLANCO",
      text: "ACE AUTOMOTIVE GROUP_MIS.EUS.MX.SN.PME.CD.TSMX.POLANCO"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCO.BOZ.LNX",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCO.BOZ.LNX",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCO.BOZ.LNX"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.AD",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.AD",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.AD"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.MSG",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.MSG",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.MSG"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.SHP",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.SHP",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.SHP"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.SWD",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.SWD",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.SWD"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.VDI",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.VDI",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CCS.VDI"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.AD",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.AD",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.AD"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.SWD",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.SWD",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.SWD"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.VDI",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.VDI",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.BOZ.VDI"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.ZEROTOUCH",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.ZEROTOUCH",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.CXC.ZEROTOUCH"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU.ORACLE",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU.ORACLE",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU.ORACLE"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU.SQL",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU.SQL",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.LBU.SQL"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.SQL.ALFA",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.SQL.ALFA",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.SQL.ALFA"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.SQL.SMURFIT",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.SQL.SMURFIT",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.SQL.SMURFIT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.VITRO",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.VITRO",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DBA.VITRO"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DPO-LNX",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DPO-LNX",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.DPO-LNX"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.LBU.WINTEL",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.LBU.WINTEL",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.LBU.WINTEL"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.PC.CLOUD.IAS",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.PC.CLOUD.IAS",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.PC.CLOUD.IAS"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SBO.BK.ST",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SBO.BK.ST",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SBO.BK.ST"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SDM.SUPPLIERS",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SDM.SUPPLIERS",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SDM.SUPPLIERS"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURE.DEFENSE",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURE.DEFENSE",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURE.DEFENSE"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.INFRA",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.INFRA",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.INFRA"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SC2.WAN",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SC2.WAN",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SC2.WAN"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SC3.WAN",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SC3.WAN",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SC3.WAN"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SMURFIT",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SMURFIT",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SMURFIT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SOC",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SOC",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SOC"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SOC.VITRO",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SOC.VITRO",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITY.SOC.VITRO"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITYUM",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITYUM",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITYUM"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITYUM.SMURFIT",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITYUM.SMURFIT",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SECURITYUM.SMURFIT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SM.TOOLS",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SM.TOOLS",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SM.TOOLS"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SYS-MANAGEMENT",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SYS-MANAGEMENT",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.SYS-MANAGEMENT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.NOC",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.NOC",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.NOC"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.PHYNET.TS",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.PHYNET.TS",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.PHYNET.TS"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SCC1.LAN",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SCC1.LAN",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SCC1.LAN"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SCC2.LAN",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SCC2.LAN",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SCC2.LAN"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SIC.LAN.VITRO",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SIC.LAN.VITRO",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SIC.LAN.VITRO"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SIC.VOICE",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SIC.VOICE",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.SIC.VOICE"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TARIFICACION",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TARIFICACION",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TARIFICACION"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TARIFICACION.SKM",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TARIFICACION.SKM",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TARIFICACION.SKM"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TELEFONIA",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TELEFONIA",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TELEFONIA"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TELEFONIA.SKM",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TELEFONIA.SKM",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.TC.TELEFONIA.SKM"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.UNIX",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.UNIX",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.UNIX"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.WINTEL.ALFA",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.WINTEL.ALFA",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.WINTEL.ALFA"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.WINTEL.VITRO",
      value: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.WINTEL.VITRO",
      text: "ACE AUTOMOTIVE GROUP_MIS.INT.MX.SN.WINTEL.VITRO"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.AO.MX.SN.AA.GDH.MX-BASIS",
      value: "ACE AUTOMOTIVE GROUP_SAP.AO.MX.SN.AA.GDH.MX-BASIS",
      text: "ACE AUTOMOTIVE GROUP_SAP.AO.MX.SN.AA.GDH.MX-BASIS"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.CCC",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.CCC",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.CCC"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.KVS",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.KVS",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.KVS"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.MQSERIES",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.MQSERIES",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.AMS.MQSERIES"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.BW.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.BW.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.BW.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.FICOTR.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.FICOTR.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.FICOTR.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.MM.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.MM.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.MM.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.PM.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.PM.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.PM.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.PP.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.PP.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.PP.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.SD.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.SD.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DAM.SD.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.BPC.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.BPC.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.BPC.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.FICO.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.FICO.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.FICO.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.HCM.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.HCM.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.HCM.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LAS.SUPT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LAS.SUPT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LAS.SUPT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LEGACY.SUPT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LEGACY.SUPT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LEGACY.SUPT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LETRA.SUPPT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LETRA.SUPPT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.LETRA.SUPPT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.MM.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.MM.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.MM.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.PI.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.PI.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.PI.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.PP.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.PP.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.PP.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.QM.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.QM.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.QM.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.SD.SUPPORT",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.SD.SUPPORT",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.DIN.LBU.SD.SUPPORT"
    },
    {
      key: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.IAMSA.MW",
      value: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.IAMSA.MW",
      text: "ACE AUTOMOTIVE GROUP_SAP.SI.MX.SN.IAMSA.MW"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.ADMIN.SK",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.ADMIN.SK",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.ADMIN.SK"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.HE.SK",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.HE.SK",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.HE.SK"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.NEMAK",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.NEMAK",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.NEMAK"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.PRINT.SK",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.PRINT.SK",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.PRINT.SK"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.SK",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.SK",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.SK"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.SW.SK",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.SW.SK",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.SW.SK"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX.IMAC",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX.IMAC",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX.IMAC"
    },
    {
      key: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX.POLANCO",
      value: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX.POLANCO",
      text: "ADIENT_MIS.EUS.MX.SN.PME.CD.TSMX.POLANCO"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CCO.BOZ.LNX",
      value: "ADIENT_MIS.INT.MX.SN.CCO.BOZ.LNX",
      text: "ADIENT_MIS.INT.MX.SN.CCO.BOZ.LNX"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CCS.AD",
      value: "ADIENT_MIS.INT.MX.SN.CCS.AD",
      text: "ADIENT_MIS.INT.MX.SN.CCS.AD"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CCS.MSG",
      value: "ADIENT_MIS.INT.MX.SN.CCS.MSG",
      text: "ADIENT_MIS.INT.MX.SN.CCS.MSG"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CCS.SHP",
      value: "ADIENT_MIS.INT.MX.SN.CCS.SHP",
      text: "ADIENT_MIS.INT.MX.SN.CCS.SHP"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CCS.SWD",
      value: "ADIENT_MIS.INT.MX.SN.CCS.SWD",
      text: "ADIENT_MIS.INT.MX.SN.CCS.SWD"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CCS.VDI",
      value: "ADIENT_MIS.INT.MX.SN.CCS.VDI",
      text: "ADIENT_MIS.INT.MX.SN.CCS.VDI"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.AD",
      value: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.AD",
      text: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.AD"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.SWD",
      value: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.SWD",
      text: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.SWD"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.VDI",
      value: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.VDI",
      text: "ADIENT_MIS.INT.MX.SN.CXC.BOZ.VDI"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.CXC.ZEROTOUCH",
      value: "ADIENT_MIS.INT.MX.SN.CXC.ZEROTOUCH",
      text: "ADIENT_MIS.INT.MX.SN.CXC.ZEROTOUCH"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.DBA.LBU",
      value: "ADIENT_MIS.INT.MX.SN.DBA.LBU",
      text: "ADIENT_MIS.INT.MX.SN.DBA.LBU"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.DBA.LBU.ORACLE",
      value: "ADIENT_MIS.INT.MX.SN.DBA.LBU.ORACLE",
      text: "ADIENT_MIS.INT.MX.SN.DBA.LBU.ORACLE"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.DBA.LBU.SQL",
      value: "ADIENT_MIS.INT.MX.SN.DBA.LBU.SQL",
      text: "ADIENT_MIS.INT.MX.SN.DBA.LBU.SQL"
    },
    {
      key: "ADIENT_MIS.INT.MX.SN.DBA.SQL.ALFA",
      value: "ADIENT_MIS.INT.MX.SN.DBA.SQL.ALFA",
      text: "ADIENT_MIS.INT.MX.SN.DBA.SQL.ALFA"
    }
  ];
  return (
    <div className="App">
      <h1>Genesys PureCloud</h1>
      <h2>Consultar DataTables mediante APIs</h2>
      <div className="inputs_Datatables">
        <Dropdown
          placeholder="Client Assigment Group"
          search
          selection
          options={optionsDrop}
        />
        <Button primary> Consultar </Button>
      </div>
    </div>
  );
}
